Added empty dependencies list
If installing role with ansible-galaxy from requirements.yml
need to specify empty list to avoid errors from ansible-galaxy

15:05 $ ansible-galaxy install -r requirements.yml
- executing: git clone https://github.com/dj-wasabi/ansible-zabbix-agent.git dj-wasabi.zabbix-agent
- executing: git archive --prefix=dj-wasabi.zabbix-agent/ --output=/var/folders/3p/m8j9q01n6vx2g25pmm8dqbtw0000gr/T/tmpU7eamc.tar 0.2.1
- extracting dj-wasabi.zabbix-agent to external/dj-wasabi.zabbix-agent
- dj-wasabi.zabbix-agent was installed successfully
Traceback (most recent call last):
  File "/Users/user/local/pyenv/bin/ansible-galaxy", line 957, in <module>
    main()
  File "/Users/user/local/pyenv/bin/ansible-galaxy", line 951, in main
    fn(args, options, parser)
  File "/Users/user/local/pyenv/bin/ansible-galaxy", line 845, in execute_install
    role_dependencies = role_data['dependencies']
KeyError: 'dependencies'